### ISSUE TITLE
Some settings about compose video

### ISSUE THREAD

**Issue by VVVVictorJ** [cchen156/Seeing-Motion-in-the-Dark#12]
Hello. I met some problem when i use the SID model to transfrom the frame which is used to compose video.I saw the demo video you released on the youtube.But when i compose the video,it just like a PPT.It not like video in the real world.I used the FFmpeg to compose those frames by setting
rate equals 24.  I was confused why your video processed by SID model looks so great.And just the static video can be process?Because the video in our daily life cannot be divide into the .DNG frames or. ARW frames.

**Comment by VVVVictorJ** [comment]
I think I know how you address this problem.

**Comment by cchen156** [comment]
I save the video using opencv.

**Comment by VVVVictorJ** [comment]
@cchen156 thank you
