### ISSUE TITLE
GPU memory problem

### ISSUE THREAD

**Issue by yuguangxie** [cchen156/Seeing-Motion-in-the-Dark#7]
Hi，could you please tell me how much GPU memory do I need when I train the network? when I use Geforce RTX2080Ti to train,i get some errors about gpu memory _allocation.
such as:     Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
or     Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Looking forward to your reply.

**Comment by yuguangxie** [comment]
When I reduce the size of the input image, there is no problem with gpu memory allocation,but I am not sure if this has any other effect

**Comment by cchen156** [comment]
I have the same issue before. If you do not have a GPU with large mem, e.g., 32GB, you can train it with smaller resolution and fine-tune on CPU. Of course that is very slow. Probably you will need to fine-tune it for a few days on CPU.

**Comment by cchen156** [comment]
I add a solution at FAQ: 4. What if my GPU memory is too small to train model?

**Comment by yuguangxie** [comment]
thanks for your solution.
