### ISSUE TITLE
About the preprocessing pipeline on raw data?

### ISSUE THREAD

**Issue by idealboy** [cchen156/Seeing-Motion-in-the-Dark#8]
Sir,

Will you have the preprocessing code released? I want to process my own data.

Thank you very much!

**Comment by cchen156** [comment]
Unfortunately, I did not take the script out after my internship. But those operations are very standard.

**Comment by idealboy** [comment]
> Unfortunately, I did not take the script out after my internship. But those operations are very standard.

Is the black level 512? and the global gain "gt_expose / in_expose"?

thank you!

**Comment by cchen156** [comment]
I think so. But I do not remember the black level exactly, which can be found from the raw file.
